import '@/styles/globals.css'
import { ThemeProvider } from '@/components/misc/theme-provider'
import { Epilogue, Manrope } from 'next/font/google'
import { type Metadata } from 'next'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { TRPCReactProvider } from '@/trpc/react'

import { Navbar } from '@/components/layout/navbar'

export const metadata: Metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
}

const font = Epilogue({ subsets: ['latin'] })

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html
        lang='en'
        className={`${font.className}`}
        suppressHydrationWarning
      >
        <body>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem
            disableTransitionOnChange
          >
            <TRPCReactProvider>
              <Navbar />
              {children}
            </TRPCReactProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
